lall: client server ping pong

client: client.c
	gcc client.c -o client
	
server: server.c
	gcc server.c -o server
	
ping: ping.c
	gcc -O2 ping.c -o ping

pong: pong.c
	gcc -O2 pong.c -o pong

clean:
	rm client server ping pong
